Implement Virtio driver, add pcap example, and add ixy-ci config
ixy-languages/ixy.rs pull request #19
Opened 2019-10-06 20:50 UTC by Bobo1239

As stated in the title this adds a Virtio driver to ixy.rs. Also adds everything necessary to test ixy.rs with [ixy-ci](https://github.com/bobo1239/ixy-ci).

I've tried to separate some changes into smaller commits so you can hopefully review this more easily.

I'll manually start an ixy-ci run on this PR for demonstration purposes. Later you'll have to add a GitHub webhook for this repository to start test runs.

2019-10-06 20:52 UTC, ackxolotl commented
Very, very cool! I'll have a look at it in the next few days, I'm quite busy right now.

2019-10-08 20:34 UTC, Bobo1239 commented
Just fyi: I have a working branch with some changes required for VirtualBox but there's currently a humongous performance disparity to the C version which I haven't pinned down yet. My current plan is to eventually expose those changes via a cargo feature-flag but that will definitely have to wait for a separate PR.

2019-10-14 13:50 UTC, ackxolotl requested changes

2019-10-14 13:50 UTC, ackxolotl commented on ixy-ci.toml
> +    "sudo apt-get install -y curl gcc",
Is `gcc` needed?

2019-10-14 13:50 UTC, ackxolotl commented on src/virtio.rs
> +        panic!("VFIO isn't supported for Virtio");
Please return `None` here

2019-10-14 14:34 UTC, Bobo1239 commented
@ixy-ci ping

2019-10-14 15:15 UTC, leanderseidlitz commented
ping @ixy-ci

2019-10-14 15:16 UTC, aevykk commented
@ixy-ci ping

2019-10-14 16:17 UTC, Bobo1239 commented
@ixy-ci test

2019-10-14 16:25 UTC, Bobo1239 commented
@ixy-ci test
(Retrying with [higher SSH connection delay](https://github.com/Bobo1239/ixy-ci/commit/92975b674111ec3795e580b45dae93de3ce10899).)

2019-10-14 17:13 UTC, ackxolotl approved these changes

2019-10-14 17:16 UTC, merged