adds use of the IOMMU with the ixy.rs driver
ixy-languages/ixy.rs pull request #8
Opened 2019-02-12 14:17 UTC by huberste

2019-02-12 18:41 UTC, ackxolotl requested changes
Since `IxgbeIommuDevice` is just a wrapper for `IxgbeDevice` with no big differences to `IxgbeDevice` apart from the initialisation procedure I think it would be better to add that code to `IxgbeDevice` in a method like `init_iommu()` and to move the check if iommu is available from `ixy_init()` in `lib.rs` to the `init()` method of `IxgbeDevice`. If all that code is in in `ixgbe.rs` then it is no longer necessary to make `IxgbeRxQueue`, `IxgbeTxQueue` and some fields in `IxgbeDevice` public. Also, what happened to `echoer.rs`? :D

2019-02-13 13:38 UTC, ackxolotl commented on src/ixgbe.rs
> +    /// When implementing non-VFIO / IOMMU devices, just return 0.
Returns VFIO container file descriptor or [\`None\`] if IOMMU is not available.

2019-02-13 15:20 UTC, huberste commented
I implemented the changes you requested and also unified the comment style (and fixed some commentation).

2019-02-13 15:21 UTC, huberste commented
I implemented the changes you requested and also unified the comment style (and fixed some commentation).

2019-02-14 17:15 UTC, ackxolotl approved these changes

2019-02-14 17:17 UTC, merged